// Import database tools and our firebase connection
import { db } from "./firebase-config.js";
import {
  collection,
    getDocs,
      query,
        orderBy,
          addDoc,
            serverTimestamp,
            } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

            // Grab all the HTML elements we need to interact with
            const questionsContainer = document.getElementById("questions-container");
            const resultsContainer = document.getElementById("results-container");
            const noticeArea = document.getElementById("notice-area");
            const questionCountEl = document.getElementById("question-count");
            const form = document.getElementById("quiz-form");
            const submitBtn = document.getElementById("submit-btn");
            const nameInput = document.getElementById("student-name");

            // The four answer letters
            const LETTERS = ["A", "B", "C", "D"];

            // These track the quiz state
            let questions = []; // all questions loaded from Firestore
            const selected = {}; // stores what letter the student picked per question
            let locked = false; // becomes true after submission so nothing can change

            // Safely convert text to HTML (prevents hacky inputs breaking the page)
            function escapeHtml(str) {
              const div = document.createElement("div");
                div.textContent = str ?? "";
                  return div.innerHTML;
                  }

                  // Show a notice message (error or info) above the quiz
                  function showNotice(message, type = "error") {
                    noticeArea.innerHTML = `<div class="notice notice--${type}">${escapeHtml(message)}</div>`;
                    }

                    function clearNotice() {
                      noticeArea.innerHTML = "";
                      }

                      // Load questions from Firestore when the page opens
                      async function loadQuestions() {
                        try {
                            // Get all documents in the "questions" collection, sorted by "order" field
                                const q = query(collection(db, "questions"), orderBy("order", "asc"));
                                    const snap = await getDocs(q);
                                        questions = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
                                          } catch (err) {
                                              console.error(err);
                                                  questionsContainer.innerHTML = "";
                                                      submitBtn.disabled = true;
                                                          showNotice("Couldn't load questions. Check your firebase-config.js values.", "error");
                                                              return;
                                                                }

                                                                  if (questions.length === 0) {
                                                                      questionsContainer.innerHTML = '<div class="empty-state">No questions yet. Add some from the <a href="admin.html">admin panel</a>.</div>';
                                                                          submitBtn.disabled = true;
                                                                              return;
                                                                                }

                                                                                  questionCountEl.textContent = `${questions.length} question${questions.length === 1 ? "" : "s"}`;
                                                                                    renderQuestions();
                                                                                    }

                                                                                    // Build the question cards and bubble buttons on the page
                                                                                    function renderQuestions() {
                                                                                      questionsContainer.innerHTML = "";

                                                                                        questions.forEach((item, index) => {
                                                                                            // Create the question card
                                                                                                const card = document.createElement("div");
                                                                                                    card.className = "question";
                                                                                                        card.dataset.id = item.id;

                                                                                                            // Question number badge + question text
                                                                                                                const head = document.createElement("div");
                                                                                                                    head.className = "question__head";
                                                                                                                        head.innerHTML = `
                                                                                                                              <span class="question__number">Q${index + 1}</span>
                                                                                                                                    <span class="question__text">${escapeHtml(item.text)}</span>
                                                                                                                                        `;
                                                                                                                                            card.appendChild(head);

                                                                                                                                                // Create the A/B/C/D bubble buttons
                                                                                                                                                    const optionsWrap = document.createElement("div");
                                                                                                                                                        optionsWrap.className = "options";

                                                                                                                                                            LETTERS.forEach((letter) => {
                                                                                                                                                                  const optionText = item.options ? item.options[letter] : undefined;
                                                                                                                                                                        if (!optionText) return; // skip if this option wasn't filled in

                                                                                                                                                                              const btn = document.createElement("button");
                                                                                                                                                                                    btn.type = "button";
                                                                                                                                                                                          btn.className = "option";
                                                                                                                                                                                                btn.dataset.letter = letter;
                                                                                                                                                                                                      btn.innerHTML = `
                                                                                                                                                                                                              <span class="bubble">${letter}</span>
                                                                                                                                                                                                                      <span>${escapeHtml(optionText)}</span>
                                                                                                                                                                                                                            `;
                                                                                                                                                                                                                                  // When clicked, record this as the student's answer
                                                                                                                                                                                                                                        btn.addEventListener("click", () => selectAnswer(item.id, letter, card));
                                                                                                                                                                                                                                              optionsWrap.appendChild(btn);
                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                      card.appendChild(optionsWrap);
                                                                                                                                                                                                                                                          questionsContainer.appendChild(card);
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                            // Record the student's selected answer and highlight it
                                                                                                                                                                                                                                                            function selectAnswer(questionId, letter, card) {
                                                                                                                                                                                                                                                              if (locked) return; // do nothing if quiz is already submitted
                                                                                                                                                                                                                                                                selected[questionId] = letter;
                                                                                                                                                                                                                                                                  // Update visual state — only the picked option gets "is-selected"
                                                                                                                                                                                                                                                                    card.querySelectorAll(".option").forEach((opt) => {
                                                                                                                                                                                                                                                                        opt.classList.toggle("is-selected", opt.dataset.letter === letter);
                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                          // Handle form submission
                                                                                                                                                                                                                                                                          form.addEventListener("submit", async (e) => {
                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                              if (locked) return;
                                                                                                                                                                                                                                                                                clearNotice();

                                                                                                                                                                                                                                                                                  // Validate name
                                                                                                                                                                                                                                                                                    const name = nameInput.value.trim();
                                                                                                                                                                                                                                                                                      if (!name) {
                                                                                                                                                                                                                                                                                          showNotice("Enter your name before submitting.");
                                                                                                                                                                                                                                                                                              nameInput.focus();
                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                      // Make sure every question has been answered
                                                                                                                                                                                                                                                                                                        const unanswered = questions.filter((q) => !selected[q.id]);
                                                                                                                                                                                                                                                                                                          if (unanswered.length > 0) {
                                                                                                                                                                                                                                                                                                              showNotice(`Answer all questions before submitting (${unanswered.length} left).`);
                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                      submitBtn.disabled = true;
                                                                                                                                                                                                                                                                                                                        submitBtn.textContent = "Grading…";

                                                                                                                                                                                                                                                                                                                          // Build the result breakdown — compare each answer to the correct one
                                                                                                                                                                                                                                                                                                                            const details = questions.map((q) => {
                                                                                                                                                                                                                                                                                                                                const pick = selected[q.id];
                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                          questionId: q.id,
                                                                                                                                                                                                                                                                                                                                                text: q.text,
                                                                                                                                                                                                                                                                                                                                                      options: q.options,
                                                                                                                                                                                                                                                                                                                                                            correct: q.correct,
                                                                                                                                                                                                                                                                                                                                                                  selected: pick,
                                                                                                                                                                                                                                                                                                                                                                        isCorrect: pick === q.correct, // true/false per question
                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                // Calculate total score
                                                                                                                                                                                                                                                                                                                                                                                  const score = details.filter((d) => d.isCorrect).length;
                                                                                                                                                                                                                                                                                                                                                                                    const total = questions.length;

                                                                                                                                                                                                                                                                                                                                                                                      // Save the submission to Firestore so admin can see it
                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                            await addDoc(collection(db, "submissions"), {
                                                                                                                                                                                                                                                                                                                                                                                                  studentName: name,
                                                                                                                                                                                                                                                                                                                                                                                                        score,
                                                                                                                                                                                                                                                                                                                                                                                                              total,
                                                                                                                                                                                                                                                                                                                                                                                                                    answers: details,
                                                                                                                                                                                                                                                                                                                                                                                                                          createdAt: serverTimestamp(), // Firebase records the exact time
                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                        showNotice("Result shown below but couldn't be saved. Check Firebase setup.", "info");
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                            // Show score card and highlight correct/wrong answers
                                                                                                                                                                                                                                                                                                                                                                                                                                              renderScoreCard(name, score, total);
                                                                                                                                                                                                                                                                                                                                                                                                                                                gradeQuizUI(details);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  lockQuiz();
                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Highlight each option as correct (green) or wrong (red) after submission
                                                                                                                                                                                                                                                                                                                                                                                                                                                  function gradeQuizUI(details) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    details.forEach((d) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const card = questionsContainer.querySelector(`.question[data-id="${d.questionId}"]`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!card) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                card.querySelectorAll(".option").forEach((opt) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const letter = opt.dataset.letter;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const isCorrectAnswer = letter === d.correct;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const isSelected = letter === d.selected;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const isWrongSelection = isSelected && !isCorrectAnswer;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              opt.classList.add("is-graded");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opt.classList.toggle("is-correct-answer", isCorrectAnswer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          opt.classList.toggle("is-wrong-selection", isWrongSelection);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Add a small tag label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const existingTag = opt.querySelector(".option__tag");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (existingTag) existingTag.remove();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let tag = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isCorrectAnswer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tag = document.createElement("span");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tag.className = "option__tag option__tag--correct";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tag.textContent = "Correct answer";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else if (isWrongSelection) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tag = document.createElement("span");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tag.className = "option__tag option__tag--your-pick";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tag.textContent = "Your answer";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (tag) opt.appendChild(tag);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Show the big score card at the top of results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function renderScoreCard(name, score, total) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const pct = total > 0 ? Math.round((score / total) * 100) : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const passed = pct >= 50;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resultsContainer.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="score-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="score-card__label">${escapeHtml(name)} · Result</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="score-card__value">${score} / ${total}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="score-card__sub">Correct answers — review your sheet below</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="score-card__pct ${passed ? "score-card__pct--pass" : "score-card__pct--fail"}">${pct}%</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resultsContainer.scrollIntoView({ behavior: "smooth", block: "start" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Prevent any further changes after submission
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function lockQuiz() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              locked = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                submitBtn.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nameInput.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Kick everything off when the page loads
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loadQuestions();